spring:
  data:
    mongodb:
      username: ${MONGODB_USER:admin}
      password: ${MONGODB_PASSWORD:admin}
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      database: chat_app
      authentication-database: admin
server:
  port: 8088